name: kilosort
channels:  
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.*
  - pip
  - psutil
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - numba
  - faiss-cpu
  - libblas=*=*mkl
  - pytest
  # CUDA
  - nvidia-ml-py
  # GUI
  - matplotlib
  - pip:
    - pyqtgraph>=0.13.0
    - qtpy
    - pyqt6
    - pyqt6.sip
