name: kilosort
channels:  
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.*
  - pip
  - psutil
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - numba
  - fsspec
  - libblas=*=*mkl
  - pytest
  - pyqt6
  - qtpy
  - pyqtgraph>=0.13.0
  # CUDA
  - nvidia-ml-py
  # GUI
  - matplotlib